Algoritmo "carro"
// Disciplina   : [PA]
// Professor   :  Edilma Di Binda
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas
// Data atual  : 25/05/2023
Var
idade: real

//ENTRADA
Inicio
escreval ("Começou")
escreval ("Digite a idade")
leia (idade)

//PROCESSAMENTO E SAÍDA
Se idade >= 18 entao
escreval ("Ok, pode passar")
senao
escreval ("Você não pode dirigir")
fimse

escreval ("Acabou")

Fimalgoritmo