Algoritmo "entre100e200"
// Disciplina   : [PA]
// Professor   :  Edilma Di Binda
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas
// Data atual  : 25/05/2023
Var
num: real


//ENTRADA
Inicio
escreval ("Começou")
escreval ("Digite o numero")
leia (num)

//PROCESSAMENTO E SAÍDA
Se num > 100 entao
e
Se num < 200 entao
escreval ("está entre")
senao
escreval ("Não está dentro")
fimse
fimse

escreval ("Acabou")

Fimalgoritmo