Algoritmo "MaiorDez"
// Disciplina   : [PA]
// Professor   :  Edilma Di Binda
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas
// Data atual  : 25/05/2023
Var
num: real

//ENTRADA
Inicio
escreval ("Começou")
escreval ("Digite a idade")
leia (num)

//PROCESSAMENTO E SAÍDA
Se num > 10 entao
escreval ("Ok, pode brincar")
senao
escreval ("Você não pode brincar")
fimse

escreval ("Acabou")

Fimalgoritmo