Algoritmo "combustivel"
// Disciplina   : PA
// Professor   : Edilma Binda
// Autor(a)    : Lucas Bardella
// Data atual  : 09/03/2023
Var
combustivel, distancia, consumo : real


// ENTRADA
Inicio
escreval ("Distancia percorrida: ")
leia (distancia)
escreval ("Combustivel gasto: ")
leia (combustivel)


// PROCESSAMENTO
consumo <- (combustivel + distancia)/2

// SAÍDA
escreval ("consumo medio: ", consumo)


Fimalgoritmo